---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: create directory
      file:
        path: "/home/oxidized/.config/oxidized/"
        state: directory
        mode: '0755'
    - name: create router.db with a pingable domain
      copy:
        dest: "/home/oxidized/.config/oxidized/router.db"
        content: |
          google.fr

  roles:
    - role: apps_oxidized
